name: Watch me
on: push

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: helaili/jekyll-action@2.3.1
            # - uses: actions/checkout@v2
            - run: bundle exec jekyll build -d public
            # - uses: FirebaseExtended/action-hosting-deploy@v0
            #   with:
            #       repoToken: "${{ secrets.GITHUB_TOKEN }}"
            #       firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BITCOIN_IL }}"
            #       projectId: bitcoin-il
